name: Build

on:
  workflow_call:
    inputs:
      docker-context:
        description: "Path to the Docker build context"
        required: true
        type: string
      dockerfile:
        description: "Path to the Dockerfile"
        required: true
        type: string
      image-name:
        description: "Image name (without repository prefix)"
        required: true
        type: string

permissions:
  contents: read
  packages: write

env:
  IMAGE_REPO: "ghcr.io/uimataso"

jobs:
  build_image_and_push_to_ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get short SHA
        id: short_sha
        run: echo "SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image to ghrc
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.docker-context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ env.IMAGE_REPO }}/${{ inputs.image-name }}:${{ steps.short_sha.outputs.SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

    outputs:
      imageTag: ${{ steps.short_sha.outputs.SHORT_SHA }}
