name: Generator - Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "generator/**"
      - "static/**"

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      docker-context: ./
      dockerfile: ./generator/Dockerfile
      image-name: my-site-generator
