name: Web Server - Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "web/**"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      docker-context: ./
      dockerfile: ./web/Dockerfile
      image-name: web-service
